# Generated by Django 4.2 on 2023-08-10 19:52

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_popular_review_restaurant_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
