# Generated by Django 4.2 on 2023-08-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_restaurant_rating_alter_restaurant_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(choices=[('BX', 'Bronx'), ('BN', 'Brooklyn'), ('MN', 'Manhattan'), ('SI', 'Staten Island'), ('QN', 'Queens')], default='MN', max_length=2),
        ),
    ]
